/**
 * Register — comparing how the Greek of one work behaves against the rest of the library.
 *
 * The index is built by scripts/build-style-index.ts and served as a static asset. Everything
 * here is pure: the view fetches once and computes distances in the browser, because 433 works
 * against 150 dimensions is a few milliseconds and it keeps the tool responsive while the
 * reader changes lenses.
 *
 * ── What the numbers mean, and what they do not ────────────────────────────────────────────
 *
 * This measures REGISTER — the level and texture of the Greek — not authorship. The validation
 * run makes the boundary concrete: Ephesians→Colossians and 1→2 Timothy come first of 432, and
 * Luke→Acts third, which is the tool working. But Hebrews also ranks first to Romans, where its
 * Greek is usually held to be the least Pauline in the New Testament. Function-word profiles
 * track GENRE at least as strongly as authorship, so the UI says "similar register", never
 * "same author", and the caveat is on the page rather than buried here.
 */

// The shape stamp is generated by the builder, so it cannot drift from the data it describes.
export { STYLE_SHAPE } from './style-shape'

export type Lens = 'register' | 'syntax' | 'vocabulary'

export interface StyleFeature {
  key: string
  label: string
  chapter: string
  /** Derived from tagger categories, so comparable across works but not exact. */
  taggerSensitive: boolean
  /** A heuristic approximation of a multi-word construction. */
  approx?: boolean
}

export interface StyleMeta {
  shape: string
  chunkWords: number
  minWords: number
  reliableWords: number
  deltaWords: string[]
  /** Accented form and short gloss per Delta word, so the table reads as Greek. */
  deltaLabels: Record<string, { d: string; g: string }>
  /** Published so a passage profiled server-side lands on the same scale as the works. */
  norm: { mu: Record<string, number>; sd: Record<string, number> }
  spread: Record<string, number>
  /** Observed range of each named axis across the library, so a bar can be drawn honestly. */
  axisRange: { periodicity: [number, number]; classicalLean: [number, number] }
  /** The library's average rate per feature — the norm two texts are both departing from. */
  center: Record<string, number>
  /** Period baselines, so a reader can ask whether a rate is Classical or of its own era. */
  periods: {
    classical: PeriodBaseline
    koine: PeriodBaseline
    /** Genre pools within each period, present only where enough voices stand behind them. */
    classicalGenres: Record<string, PeriodBaseline>
    koineGenres: Record<string, PeriodBaseline>
    /** Every work's own genre, so a comparison can default to like with like. */
    genreOfWork: Record<string, string>
    /** Epic verse, in neither baseline — an artificial dialect belonging to no prose period. */
    excluded: { work: string; label: string; words: number }[]
  }
  /** Per lens, [as close as anything gets, no closer than chance] — the result bar's scale. */
  barScale: Record<string, [number, number]>
  passageCorpora: string[]
  features: StyleFeature[]
}

/** One book of a passage-capable corpus: its work id, and [chapter, words] for each chapter. */
export interface PassageBook {
  id: string
  label: string
  work: string
  ch: [number, number][]
}
export type PassageManifest = Record<string, PassageBook[]>

/** What /api/register/passage returns. */
export interface PassageProfile {
  n: number
  rates: Record<string, number>
  delta: number[]
  /** Content lemmas as rates per 1,000 — the vocabulary lens needs them for a passage too. */
  content: [string, number][]
  reliable: boolean
  span: { fromCh: number; toCh: number }
}

/**
 * Dress a profiled passage as a unit so it can go through the same ranking as everything else.
 *
 * The synthetic `work` id deliberately does not collide with any real one, so the passage's own
 * book stays in its results — seeing how far Luke 1-2 sits from Luke is the point, not noise.
 */
export function passageUnit(
  p: PassageProfile, corpus: string, book: string, label: string,
): StyleUnit {
  return {
    corpus, work: `passage:${corpus}/${book}/${p.span.fromCh}-${p.span.toCh}`, label,
    kind: 'work', idx: 0, n: p.n, reliable: p.reliable, rates: p.rates, delta: p.delta,
  }
}

export interface StyleUnit {
  corpus: string
  work: string
  label: string
  kind: 'work' | 'chunk'
  idx: number
  n: number
  /** False when the unit is too short for the distance to be steady — the UI must say so. */
  reliable: boolean
  rates: Record<string, number>
  delta: number[]
  /** Share of clause-linking done by subordination — Aristotle's εἰρομένη against κατεστραμμένη. */
  periodicity?: number
  /** Position between the Classical and Koine centroids: +1 Classical mean, −1 Koine mean. */
  classicalLean?: number
}

export interface Neighbour {
  unit: StyleUnit
  distance: number
}

/** Burrows's Delta: mean absolute difference of z-scored function-word frequencies. */
export function delta(a: StyleUnit, b: StyleUnit): number {
  let sum = 0
  const n = Math.min(a.delta.length, b.delta.length)
  for (let i = 0; i < n; i++) sum += Math.abs(a.delta[i] - b.delta[i])
  return sum / n
}

/** Distance over the syntactic rates, each scaled by its spread across the corpus. */
export function syntaxDistance(a: StyleUnit, b: StyleUnit, spread: Record<string, number>): number {
  const keys = Object.keys(a.rates)
  let sum = 0
  for (const k of keys) {
    const s = spread[k] || 1
    sum += Math.abs((a.rates[k] ?? 0) - (b.rates[k] ?? 0)) / s
  }
  return sum / keys.length
}

/** Per-feature standard deviation across whole works — the scale for syntaxDistance. */
export function featureSpread(units: StyleUnit[]): Record<string, number> {
  const works = units.filter(u => u.kind === 'work')
  const out: Record<string, number> = {}
  if (!works.length) return out
  for (const k of Object.keys(works[0].rates)) {
    const xs = works.map(w => w.rates[k] ?? 0)
    const m = xs.reduce((a, b) => a + b, 0) / xs.length
    out[k] = Math.sqrt(xs.reduce((a, b) => a + (b - m) ** 2, 0) / xs.length) || 1
  }
  return out
}

/** public/data/style/vocab.json: the per-work content lists, plus accented forms where known. */
export interface VocabFile {
  shape: string
  labels: Record<string, string>
  works: Record<string, [string, number][] | null>
  /** Content-word rates per period. A lemma absent from a map is nought there. */
  periods: { classical: Record<string, number>; koine: Record<string, number> }
}
export type VocabIndex = VocabFile['works']

/**
 * Vocabulary distance: one minus the cosine similarity of two works' content-word profiles.
 *
 * This is a different question from the other two lenses and the page says so. Function words
 * and syntax are habits a writer carries between subjects; content words are largely WHAT the
 * text is about. Judith and Tobit score alike here partly because both are Jewish diaspora
 * novellas, not only because their Greek is alike — which is useful to see, as long as nobody
 * mistakes it for the same measurement.
 */
export function vocabDistance(a: [string, number][], b: [string, number][]): number {
  const A = new Map(a)
  let dot = 0, na = 0, nb = 0
  for (const [, v] of a) na += v * v
  for (const [l, v] of b) {
    nb += v * v
    const x = A.get(l)
    if (x !== undefined) dot += x * v
  }
  if (!na || !nb) return 1
  return 1 - dot / Math.sqrt(na * nb)
}

export interface SharedWord {
  lemma: string
  target: number
  other: number
  /** The weaker of the two rates — how much vocabulary they genuinely hold in common. */
  shared: number
  /**
   * The same word's rate in each period. A nought here means something different from a nought
   * in the other two lenses: content words track subject, so Ἰησοῦς is missing from Classical
   * prose because of what that prose is about, not because of how it is written.
   */
  classical: number
  koine: number
}

/** The "why" for the subject-word lens: the content words both texts lean on. */
export function explainVocab(
  a: [string, number][], b: [string, number][], periods?: VocabFile['periods'], limit = 10,
): SharedWord[] {
  const B = new Map(b)
  const out: SharedWord[] = []
  for (const [lemma, x] of a) {
    const y = B.get(lemma)
    if (y === undefined) continue
    out.push({
      lemma, target: x, other: y, shared: Math.min(x, y),
      classical: periods?.classical[lemma] ?? 0,
      koine: periods?.koine[lemma] ?? 0,
    })
  }
  return out.sort((p, q) => q.shared - p.shared).slice(0, limit)
}

export interface NeighbourOptions {
  /** Drop candidates from the target's own corpus — "what OUTSIDE the NT reads like this?" */
  excludeSameCorpus?: boolean
  /** Hide units too short to be steady. */
  reliableOnly?: boolean
  limit?: number
  /** Required by the vocabulary lens; ignored by the others. */
  vocab?: VocabIndex
  /** A passage's own content list, which is not in the prebuilt index. */
  targetVocab?: [string, number][] | null
}

export function neighbours(
  target: StyleUnit,
  units: StyleUnit[],
  lens: Lens,
  spread: Record<string, number>,
  opts: NeighbourOptions = {},
): Neighbour[] {
  const { excludeSameCorpus = false, reliableOnly = true, limit = 25, vocab, targetVocab } = opts
  const mine = targetVocab ?? vocab?.[target.work] ?? null
  const measure = lens === 'syntax'
    ? (u: StyleUnit) => syntaxDistance(target, u, spread)
    : lens === 'vocabulary'
      ? (u: StyleUnit) => (mine && vocab?.[u.work] ? vocabDistance(mine, vocab[u.work]!) : 1)
      : (u: StyleUnit) => delta(target, u)

  return units
    .filter(u => u.kind === 'work' && u.work !== target.work)
    .filter(u => (excludeSameCorpus ? u.corpus !== target.corpus : true))
    .filter(u => (reliableOnly ? u.reliable : true))
    // On the vocabulary lens a work with no list cannot be scored; ranking it at the maximum
    // distance would quietly park it at the bottom as though it had been measured.
    .filter(u => (lens === 'vocabulary' ? !!vocab?.[u.work] : true))
    .map(u => ({ unit: u, distance: measure(u) }))
    .sort((a, b) => a.distance - b.distance)
    .slice(0, limit)
}

/* ── what two texts have in common ───────────────────────────────────────────
 * The tool's claim is that two texts read alike, and the evidence for that claim is what they
 * SHARE — yet the feature table led with the biggest differences, which argues the opposite
 * case. These functions rank agreement instead.
 *
 * Agreement alone is not evidence, though: two texts that both use the optative zero times a
 * thousand words agree perfectly and have told you nothing, because so does most of the
 * library. What counts is a habit they share AND that sets them both apart — both far above the
 * library's average, or both far below it, and by about the same amount. So the score is
 *
 *     min(|zA|, |zB|)  −  |zA − zB|          when zA and zB fall on the same side of the mean
 *
 * — how far the weaker of the two departs from the norm, less how far apart they are. A trait
 * they both push hard in the same direction scores high; one they merely both possess scores
 * near zero; one they disagree about is excluded.
 *
 * A shared ABSENCE needs one more guard. "Both never use μᾶλλον" is a real observation when the
 * library averages 1.3 per 1,000 and the text runs 2,000 words — it predicts about two and a
 * half occurrences, so nought is as likely as not. It is a real observation about μέν, which
 * the library averages at 11 per 1,000 and which should therefore have turned up twenty-two
 * times. So a trait scored BELOW the mean is only admitted when the library's own rate predicts
 * at least EXPECTED_FLOOR occurrences in both texts; otherwise the zero is sampling noise
 * dressed as evidence, and short passages fill with it.
 */
const EXPECTED_FLOOR = 5

/** Would the library's average rate predict enough occurrences here for a zero to mean anything? */
const absenceIsMeaningful = (average: number, nA: number, nB: number) =>
  Math.min(average * nA, average * nB) / 1000 >= EXPECTED_FLOOR
export interface PeriodBaseline {
  features: Record<string, number>
  words: Record<string, number>
  members: { author: string; corpus: string; work?: string; works: number; words: number }[]
}

export interface SharedTrait {
  feature: StyleFeature
  target: number
  other: number
  /** The library's average, so a reader can see which way the pair departs from it. */
  average: number
  /** The same rate in fourth-century Attic prose, and in the Greek of the Hellenistic era. */
  classical: number
  koine: number
  score: number
}

/**
 * Which pool each baseline column is drawn from.
 *
 * "Is 88 occurrences of καί a lot?" has no answer until you say a lot COMPARED WITH WHAT, and
 * the honest comparisons are several: against all prose of the period, against the same genre,
 * or against a genre deliberately unlike it — which is how a reader establishes that a figure
 * is a feature of the register rather than of the subject or the century.
 *
 * `null` means the period has no pool for that genre, and the interface must say so rather than
 * substitute the period average under a genre heading. That is not hypothetical: this library
 * holds no classical letters at all.
 */
export interface BaselinePair {
  genre: string | null
  classical: PeriodBaseline | null
  koine: PeriodBaseline | null
}

export const ALL_PROSE = 'all'

export function baselinePair(meta: StyleMeta, genre: string): BaselinePair {
  const p = meta.periods
  if (!p) return { genre: null, classical: null, koine: null }
  if (genre === ALL_PROSE) return { genre: null, classical: p.classical, koine: p.koine }
  return {
    genre,
    classical: p.classicalGenres?.[genre] ?? null,
    koine: p.koineGenres?.[genre] ?? null,
  }
}

/** Every genre either period can supply, for the selector. */
export function availableGenres(meta: StyleMeta): string[] {
  const p = meta.periods
  if (!p) return []
  const all = new Set([
    ...Object.keys(p.classicalGenres ?? {}),
    ...Object.keys(p.koineGenres ?? {}),
  ])
  return Array.from(all).sort()
}

export function sharedFeatures(
  target: StyleUnit, other: StyleUnit, meta: StyleMeta, base: BaselinePair, limit = 8,
): SharedTrait[] {
  return meta.features
    .map(f => {
      const a = target.rates[f.key] ?? 0
      const b = other.rates[f.key] ?? 0
      const mid = meta.center?.[f.key] ?? 0
      const sd = meta.spread?.[f.key] || 1
      const za = (a - mid) / sd
      const zb = (b - mid) / sd
      const agree = za === 0 || zb === 0 ? false : (za > 0) === (zb > 0)
      const admissible = agree
        && (za > 0 || absenceIsMeaningful(mid, target.n, other.n))
      return {
        feature: f, target: a, other: b, average: mid,
        classical: base.classical ? base.classical.features[f.key] ?? 0 : NaN,
        koine: base.koine ? base.koine.features[f.key] ?? 0 : NaN,
        score: admissible ? Math.min(Math.abs(za), Math.abs(zb)) - Math.abs(za - zb) : -Infinity,
      }
    })
    .filter(r => r.score > 0)
    .sort((x, y) => y.score - x.score)
    .slice(0, limit)
}

export interface SharedWordTrait {
  lemma: string
  display: string
  gloss: string
  target: number
  other: number
  average: number
  classical: number
  koine: number
  score: number
}

/** The same argument over the function words, whose z-scores the index already carries. */
export function sharedWords(
  target: StyleUnit, other: StyleUnit, meta: StyleMeta, base: BaselinePair, limit = 8,
): SharedWordTrait[] {
  const { mu } = meta.norm
  return meta.deltaWords
    .map((lemma, i) => {
      const za = target.delta[i] ?? 0
      const zb = other.delta[i] ?? 0
      const sd = meta.norm.sd[lemma] ?? 0
      const label = meta.deltaLabels?.[lemma]
      const avg = mu[lemma] ?? 0
      const agree = za === 0 || zb === 0 ? false : (za > 0) === (zb > 0)
      const admissible = agree
        && (za > 0 || absenceIsMeaningful(avg, target.n, other.n))
      return {
        lemma,
        display: label?.d || lemma,
        gloss: label?.g || '',
        target: Math.max(0, za * sd + avg),
        other: Math.max(0, zb * sd + avg),
        average: avg,
        classical: base.classical ? base.classical.words[lemma] ?? 0 : NaN,
        koine: base.koine ? base.koine.words[lemma] ?? 0 : NaN,
        score: admissible ? Math.min(Math.abs(za), Math.abs(zb)) - Math.abs(za - zb) : -Infinity,
      }
    })
    .filter(r => r.score > 0)
    .sort((x, y) => y.score - x.score)
    .slice(0, limit)
}

export interface FeatureGap {
  feature: StyleFeature
  target: number
  other: number
  /** Difference in units of the feature's own spread — what makes the gap notable, not just big. */
  z: number
}

/** The "why": which features separate two works most, scaled so rare features can still rank. */
export function explain(
  target: StyleUnit,
  other: StyleUnit,
  features: StyleFeature[],
  spread: Record<string, number>,
  limit = 10,
): FeatureGap[] {
  return features
    .map(f => {
      const a = target.rates[f.key] ?? 0
      const b = other.rates[f.key] ?? 0
      return { feature: f, target: a, other: b, z: Math.abs(a - b) / (spread[f.key] || 1) }
    })
    .sort((x, y) => y.z - x.z)
    .slice(0, limit)
}

export interface WordGap {
  lemma: string
  /** Accented form, for display. */
  display: string
  gloss: string
  target: number
  other: number
  z: number
}

/**
 * The "why" for the FUNCTION-WORD lens.
 *
 * The ranking and its explanation have to be computed from the same thing, or the page says one
 * number and justifies it with another. Delta ranks on z-scored lemma frequencies, so this
 * ranks the same 150 dimensions by the same difference, and converts each back to a rate per
 * 1,000 words for reading — the z-score is what the distance is made of, the rate is what a
 * reader can check against a text.
 */
export function explainDelta(
  target: StyleUnit, other: StyleUnit, meta: StyleMeta, limit = 10,
): WordGap[] {
  const { mu, sd } = meta.norm
  return meta.deltaWords
    .map((lemma, i) => {
      const za = target.delta[i] ?? 0
      const zb = other.delta[i] ?? 0
      const back = (z: number) => z * (sd[lemma] ?? 0) + (mu[lemma] ?? 0)
      const label = meta.deltaLabels?.[lemma]
      return {
        lemma,
        display: label?.d || lemma,
        gloss: label?.g || '',
        target: Math.max(0, back(za)),
        other: Math.max(0, back(zb)),
        z: Math.abs(za - zb),
      }
    })
    .sort((a, b) => b.z - a.z)
    .slice(0, limit)
}

/** Chunks of one work, for showing that a long work is not stylistically uniform. */
export function chunksOf(work: string, units: StyleUnit[]): StyleUnit[] {
  return units.filter(u => u.kind === 'chunk' && u.work === work).sort((a, b) => a.idx - b.idx)
}

/**
 * Corpus → message key. The corpus name is chrome, so it is translated; the WORK titles are
 * not, beyond the biblical books that book-names.ts already covers — a prose title here is
 * also how the work is cited, and text-names.ts keys those by their last segment with the
 * author stripped, which does not reconstruct "Josephus, Antiquities". English is the
 * documented fallback rather than a half-translated citation.
 */
export const CORPUS_KEY: Record<string, string> = {
  GNT: 'reg.corpus.gnt',
  LXX: 'reg.corpus.lxx',
  josephus: 'reg.corpus.josephus',
  philo: 'reg.corpus.philo',
  'apostolic-fathers': 'reg.corpus.apostolicFathers',
  pseudepigrapha: 'reg.corpus.pseudepigrapha',
  eusebius: 'reg.corpus.eusebius',
  justin: 'reg.corpus.justin',
  greco: 'reg.corpus.greco',
}

/** True for the corpora whose work ids are OSIS book ids, so book-names.ts can localize them. */
export const isBiblical = (corpus: string) => corpus === 'GNT' || corpus === 'LXX'
