// GENERATED by scripts/build-style-index.ts — do not edit.
// A fingerprint of the shape of public/data/style. The interface refuses an index whose
// stamp differs from this and refetches past the cache; see the note in the builder.
export const STYLE_SHAPE = 'be910e2929fb'
