// Glosses from: A Modern Biblical Greek Vocab Builder
// Glanz, Kostuyk & Vine. Used with permission. Do not distribute.
// Keys are dictionary-form lexemes (no diacritics normalization needed).

export const VOCAB_GLOSSES: Record<string, string> = {
  'αὐτός': 'he, she, it, himself, herself, itself; even, very; same',
  'γάρ': 'for',
  'δέ': 'but, and',
  'ἐγώ': 'I',
  'εἰμί': 'am, exist',
  'εἰς': 'into, in',
  'ἐκ': 'from out, from',
  'ἐν': '(with dat.) in',
  'θεός': 'god',
  'Ἰησοῦς': 'Jesus, Joshua',
  'καί': 'and, also, likewise',
  'λέγω': 'say, tell',
  'μή': 'not, lest',
  'ὁ': 'the',
  'ὅς': 'who, which, what, that',
  'ὅτι': 'that, since, because',
  'οὐ': 'no, not',
  'οὗτος': 'this, he, she, it',
  'πᾶς': 'all, every',
  'σύ': 'you',
  'ἀλλά': 'but, rather, yet',
  'ἄνθρωπος': 'man, human being, person',
  'ἀπό': '(with gen.) from, away from',
  'γίνομαι': 'am born, become, happen',
  'διά': '(with gen.) through; (with acc.) on account of, because of',
  'εἰ': 'if',
  'ἐπί': '(with gen.) over, upon; (with dat.) on, in; (with acc.) on, against',
  'ἔρχομαι': 'come, go',
  'ἔχω': 'have, hold',
  'ἵνα': 'in order that, so that',
  'κατά': '(with gen.) down, against; (with acc.) according to, along',
  'κύριος': 'lord, master, the Lord',
  'ὁράω': 'see, look upon',
  'οὖν': 'therefore, then',
  'ποιέω': 'do, make',
  'πρός': '(with acc.) to, towards, with, (with dat.) near, at',
  'τίς': 'who, which, what',
  'τὶς': 'anyone, anything; someone, something',
  'Χριστός': 'the Anointed One, the Messiah, the Christ',
  'ὡς': 'as, like, so',
  'ἀδελφός': 'brother',
  'ἀκούω': 'hear, listen',
  'δίδωμι': 'offer, give',
  'ἐάν': 'if',
  'ἑαυτοῦ': 'himself, herself, itself',
  'εἷς': 'one',
  'ἤ': 'or, either',
  'ἡμέρα': 'day',
  'λαλέω': 'speak, say',
  'λαμβάνω': 'receive, take',
  'λόγος': 'word, speech',
  'μαθητής': 'learner, disciple',
  'μετά': '(with gen.) with; (with acc.) after, behind',
  'οἶδα': 'know, remember',
  'οὐρανός': 'sky, heaven',
  'πατήρ': 'father, ancestor',
  'περί': '(with gen.) about, concerning; (with acc.) around, near',
  'πνεῦμα': 'wind, breath, spirit',
  'πολύς': 'much, many, often',
  'υἱός': 'son, descendent',
  'ἅγιος': 'holy, sacred',
  'ἀνήρ': 'man',
  'ἀποκρίνομαι': 'answer, reply',
  'γῆ': 'earth, land',
  'γινώσκω': 'come to know, learn',
  'γυνή': 'woman, wife',
  'δύναμαι': 'am able, can',
  'ἐκεῖνος': 'that',
  'ἐξέρχομαι': 'go out, come out',
  'θέλω': 'will, wish, desire',
  'Ἰουδαῖος': 'Jewish, Judean',
  'μέγας': 'large, great',
  'νόμος': 'law',
  'ὄνομα': 'name',
  'οὐδείς': 'no one, nothing',
  'οὕτω': 'thus, so, in this manner',
  'πιστεύω': 'believe (in), have faith in, trust',
  'πίστις': 'faith, belief, trust',
  'τέ': 'and, both',
  'ὑπό': '(with gen.) by; (with acc.) under',
  'ἄγγελος': 'angel, messenger',
  'ἁμαρτία': 'sin',
  'ἄν': '(an untranslatable conditional particle)',
  'βασιλεία': 'kingdom, reign',
  'γράφω': 'write',
  'δόξα': 'glory, splendor, brightness',
  'ἔθνος': 'nation, the Gentiles',
  'εἰσέρχομαι': 'go in, come in, enter',
  'ἔργον': 'work, labor',
  'εὑρίσκω': 'find, discover',
  'καθώς': 'just as, as',
  'καρδία': 'heart',
  'κόσμος': 'the world, universe',
  'μέν...': 'indeed, on the one hand (but often untranslatable)',
  'ὄχλος': 'crowd, multitude',
  'παρά': '(with gen.) from; (with dat.) at, by; (with acc.) by, near',
  'Παῦλος': 'Paul',
  'πόλις': 'city',
  'τότε': 'then',
  'χείρ': 'hand',
  'ἀγαπάω': 'love',
  'ἄλλος': 'other, another',
  'ἀφίημι': 'leave, let go, pardon',
  'ἐγείρω': 'raise',
  'ἕως': 'until, as far as',
  'ζάω': 'live',
  'ἵστημι': 'cause to stand, place, set',
  'καλέω': 'call, invite',
  'λαός': 'people, crowd',
  'νῦν': 'now, already',
  'ὅστις': 'whosoever, whichsoever, whatsoever',
  'οὐδέ': 'neither, nor,  and not',
  'πάλιν': 'again, further',
  'Πέτρος': 'Peter',
  'πορεύομαι': 'go, proceed',
  'προφήτης': 'prophet',
  'σάρξ': 'flesh, body',
  'σῶμα': 'body, flesh',
  'ὑπέρ': '(with gen.) on behalf of; (with acc.) above',
  'χάρις': 'grace, favor, kindness',
  'αἰών': 'age, eternity',
  'ἀμήν': 'truly, amen, so let it be',
  'ἀπέρχομαι': 'depart, go away',
  'ἀποστέλλω': 'send away, dismiss, send out',
  'ἀρχιερεύς': 'high priest',
  'βάλλω': 'throw, place',
  'βλέπω': 'look, see',
  'δοῦλος': 'slave',
  'δύναμις': 'power, strength',
  'δύο': 'two',
  'ζωή': 'life',
  'θάνατος': 'death',
  'Ἰωάννης': 'John',
  'μένω': 'remain, abide, stay',
  'νεκρός': 'dead, a corpse',
  'ὅταν': 'when, whenever',
  'παραδίδωμι': 'hand over, hand down, entrust',
  'πῶς': 'how, in what manner',
  'σύν': '(with dat.) with',
  'φωνή': 'sound, voice',
  'ἀγαθός': 'good',
  'ἀγάπη': 'love',
  'ἀλήθεια': 'truth, truthfulness',
  'ἀνίστημι': 'raise, rise, stand up',
  'ἀποθνῄσκω': 'am dying, die',
  'βασιλεύς': 'king, ruler',
  'δεῖ': 'it is necessary, one must',
  'ἐκκλησία': 'assembly, congregation, church',
  'ἐξουσία': 'power, authority',
  'ζητέω': 'seek, look for, ask',
  'ἴδιος': 'one\'s own, personal',
  'κρίνω': 'judge, decide',
  'μέλλω': 'am about to, intend',
  'οἶκος': 'house, household, dwelling',
  'ὅλος': 'entire, whole, complete',
  'ὅσος': 'as great, as far, how far',
  'παρακαλέω': 'comfort, invite, exhort',
  'σῴζω': 'save, heal',
  'ψυχή': 'soul, life',
  'ὥρα': 'hour, season',
  'αἷμα': 'blood',
  'αἴρω': 'raise, lift up, take away',
  'ἀλλήλων': 'one another, each other',
  'ἄρτος': 'bread',
  'γεννάω': 'bring forth, give birth to',
  'διδάσκω': 'teach',
  'εἶπον': 'say, speak',
  'ἐκεῖ': 'there, to that place',
  'ἕτερος': 'another, different, other',
  'καλός': 'beautiful, good',
  'ὁδός': 'way, road, journey',
  'ὅτε': 'when',
  'ὀφθαλμός': 'eye',
  'περιπατέω': 'go about, walk around',
  'πρῶτος': 'first, before',
  'τέκνον': 'child, descendent',
  'τίθημι': 'put, place',
  'τόπος': 'place',
  'Φαρισαῖος': 'Pharisee',
  'φοβέομαι': 'fear, am terrified',
  'ἀκολουθέω': 'accompany, follow',
  'ἀπόλλυμι': 'destroy, ruin',
  'δικαιοσύνη': 'justice, righteousness',
  'εἰρήνη': 'peace',
  'ἐνώπιον': 'in the presence of, before',
  'ἑπτά': 'seven',
  'ἐσθίω': 'eat',
  'ἔτι': 'still, yet, even now',
  'εὐθέως': 'immediately, soon',
  'θάλασσα': 'sea, lake',
  'κάθημαι': 'sit, sit down',
  'καιρός': 'time, right time',
  'μηδείς': 'no one, nothing',
  'οἰκία': 'house, household',
  'οὔτε': 'and not, neither, nor',
  'πίπτω': 'fall',
  'πληρόω': 'fill, make full, finish',
  'πούς': 'foot',
  'προσέρχομαι': 'come near,  go to, approach',
  'προσεύχομαι': 'pray',
  'ἀναβαίνω': 'go up, embark, ascend',
  'ἀνοίγω': 'open',
  'ἀπόστολος': 'apostle, messenger',
  'ἄρχω': 'rule, be first; (mid.) begin',
  'δίκαιος': 'just, righteous',
  'ἕκαστος': 'each, every one',
  'ἐκβάλλω': 'throw out, expel, cast',
  'ἐμός': 'mine, myself',
  'κἀγώ': 'and I, but I',
  'καταβαίνω': 'go down, come down',
  'μᾶλλον': 'more, rather',
  'μήτηρ': 'mother',
  'Μωϋσῆς': 'Moses',
  'ὅπου': 'where, since, insofar as',
  'πέμπω': 'send',
  'πονηρός': 'evil, bad',
  'στόμα': 'mouth, speech',
  'ὕδωρ': 'water',
  'ὑπάγω': 'go away, depart',
  'ὥστε': 'so that, therefore',
  'Ἀβραάμ': 'Abraham',
  'ἄγω': 'lead',
  'αἰτέω': 'ask, request, ask for',
  'αἰώνιος': 'eternal',
  'ἀποκτείνω': 'put to death, kill',
  'βαπτίζω': 'dip, baptize',
  'δώδεκα': 'twelve',
  'εὐαγγέλιον': 'gospel, the Good News',
  'ἱερός': 'temple',
  'Ἱεροσόλυμα': 'Jerusalem',
  'κεφαλή': 'head',
  'μαρτυρέω': 'testify, bear witness',
  'πίνω': 'drink',
  'πρόσωπον': 'face',
  'πῦρ': 'fire',
  'σημεῖον': 'sign, miracle',
  'Σίμων': 'Simon',
  'τηρέω': 'keep, guard, observe',
  'φῶς': 'light, source of light',
  'χαίρω': 'rejoice, am glad',
  'ἀπολύω': 'let go, send away,  set free',
  'γραμματεύς': 'scribe, man of learning',
  'δαιμόνιον': 'demon, evil spirit',
  'εἴτε': 'and if, whether, if',
  'ἐντολή': 'commandment, order',
  'ἐρωτάω': 'ask, question, request',
  'Ἰσραήλ': 'Israel',
  'καρπός': 'fruit, gain, crop',
  'μόνος': 'alone, only',
  'ὄρος': 'mountain, hill',
  'πιστός': 'trustworthy, faithful, believing',
  'πλοῖον': 'ship, vessel, boat',
  'πρεσβύτερος': 'old; (as noun) elder',
  'ῥῆμα': 'word, saying; thing, matter',
  'σάββατον': 'Sabbath, week',
  'τρεῖς': 'three',
  'φέρω': 'carry, bear',
  'φημί': 'say',
  'ἀγαπητός': 'beloved, dear',
  'ἀσπάζομαι': 'greet, salute',
  'Γαλιλαία': 'Galilee',
  'Δαυίδ': 'David',
  'διδάσκαλος': 'teacher',
  'δοκέω': 'think, seem, believe',
  'δοξάζω': 'glorify, honor, praise',
  'ἔξω': 'outside, out',
  'ἤδη': 'now, already',
  'θέλημα': 'will, wish, desire',
  'θρόνος': 'throne',
  'ἱμάτιον': 'outer garment, garment',
  'κηρύσσω': 'proclaim, herald, preach',
  'λίθος': 'stone',
  'νύξ': 'night, night-time',
  'προσκυνέω': 'worship',
  'συνάγω': 'gather together',
  'ὑπάρχω': 'am, exist, be present',
  'χαρά': 'joy, gladness',
  'ὧδε': 'here',
  'ἀρχή': 'beginning; ruler, authority',
  'δεξιός': 'on the right hand, right',
  'δέχομαι': 'take, receive',
  'διό': 'therefore, for this reason',
  'ἐλπίς': 'hope, expectation',
  'ἐπερωτάω': 'question, ask (a question)',
  'ἔσχατος': 'last, finally',
  'εὐαγγελίζω': 'preach the Good News',
  'θεωρέω': 'see, perceive',
  'κράζω': 'cry out, cry, call out',
  'Μαρία': 'Mary',
  'μέσος': 'middle, in the middle',
  'μηδέ': 'and not, but not',
  'Πιλᾶτος': 'Pilate',
  'συναγωγή': 'assembly, congregation, synagogue',
  'τοιοῦτος': 'of such a kind, such, such as this',
  'τρίτος': 'third',
  'χρόνος': 'time, season',
  'ἀποδίδωμι': 'give away, give up; render',
  'ἄχρι': 'as far as, up to, until',
  'γλῶσσα': 'tongue, language',
  'γραφή': 'writing',
  'ἔμπροσθεν': '(adverb) ahead; (prep., with gen.) in front of, before',
  'ἐπαγγελία': 'promise',
  'ἔτος': 'year',
  'κακός': 'bad, evil',
  'μακάριος': 'happy, blessed',
  'ὅπως': '(adv.) how; (conj.) in order that, so that, that',
  'οὐχί': 'by no means, not at all, not',
  'παιδίον': 'infant, young child',
  'παραβολή': 'parable, comparison',
  'παραλαμβάνω': 'take, receive, take with',
  'πείθω': 'convince, persuade; trust in',
  'σοφία': 'wisdom',
  'σπείρω': 'sow, spread, scatter',
  'τυφλός': 'blind',
  'φανερόω': 'reveal, make known',
  'χρεία': 'need, necessity',
  'ἁμαρτωλός': 'sinful',
  'ἀπαγγέλλω': 'report, announce, proclaim',
  'διώκω': 'hasten; pursue, persecute',
  'ἔρημος': 'deserted, empty; (as a noun) desert, wilderness',
  'θηρίον': 'wild beast, animal',
  'θλῖψις': 'persecution, affliction, distress, tribulation',
  'καθίζω': 'sit down, cause to sit down, stay (intrans.)',
  'κρατέω': 'take hold, hold fast',
  'κρίσις': 'judging, judgment',
  'μικρός': 'little, small',
  'ναός': 'temple, shrine',
  'οὐαί': 'woe!, alas!',
  'οὐκέτι': 'no longer, no more',
  'πρό': '(with gen.) before, in front of',
  'προσφέρω': 'bring to, offer',
  'σταυρόω': 'crucify',
  'σωτηρία': 'deliverance, salvation',
  'φόβος': 'fear',
  'φυλακή': 'guard, prison, watch',
  'ἁμαρτάνω': 'sin',
  'ἀνάστασις': 'resurrection',
  'γενεά': 'generation, family',
  'δεύτερος': 'second, in the second place',
  'δέομαι': 'bind, tie',
  'ἐγγίζω': 'come near, approach',
  'ἐπιγινώσκω': 'come to know, recognize, understand',
  'Ἡρῴδης': 'Herod',
  'θαυμάζω': 'wonder, marvel',
  'θεραπεύω': 'care for, heal',
  'Ἰάκωβος': 'James',
  'Ἰουδαία': 'Judea',
  'καινός': 'fresh, new',
  'κατοικέω': 'dwell in, live',
  'λύω': 'loose, untie, set free',
  'μέρος': 'part, portion',
  'ὅμοιος': 'like, similar to',
  'πότε': 'when, at what time',
  'ποῦ': 'where',
  'σπέρμα': 'seed, offspring',
  'ἄξιος': 'worthy, fit',
  'διέρχομαι': 'pass through, go through',
  'ἐπιτίθημι': 'put, place upon, lay on',
  'ἐργάζομαι': 'work, do, accomplish',
  'ἑτοιμάζω': 'make ready, prepare',
  'εὐλογέω': 'bless',
  'ἱκανός': 'sufficient, large',
  'κλαίω': 'weep, mourn, cry',
  'λογίζομαι': 'reckon, count, think',
  'λοιπός': 'remaining, left, the rest',
  'ὀλίγος': 'few, little',
  'πάντοτε': 'always, at all times',
  'παρίστημι': 'present, come up to and stand by',
  'σεαυτοῦ': 'of yourself, yourself',
  'σήμερον': 'today, now',
  'τέλος': 'end, purpose',
  'τέσσαρες': 'four',
  'τιμή': 'price, honor, value',
  'φωνέω': 'summon, call',
  'χωρίς': 'apart from, without',
  'ἄρχων': 'ruler, lord, authority',
  'βούλομαι': 'will, desire, wish',
  'διάβολος': 'the Slanderer, the Devil',
  'διακονέω': 'wait at table, serve',
  'δικαιόω': 'make righteous, justify',
  'ἐμαυτοῦ': 'of myself, myself',
  'ἐπιθυμία': 'desire, lust, longing',
  'εὐχαριστέω': 'thank, give thanks',
  'θύρα': 'door',
  'Ἰούδας': 'Judas, Jude',
  'μισέω': 'hate, detest',
  'μνημεῖον': 'tomb, sepulcher, grave',
  'οἰκοδομέω': 'build, build up, edify',
  'πάσχω': 'suffer, endure',
  'πειράζω': 'try, tempt, test',
  'πέντε': 'five',
  'περισσεύω': 'have an abundance, rich',
  'πλανάω': 'lead astray, deceive',
  'πράσσω': 'do, accomplish',
  'ὑποτάσσω': 'subject, subordinate',
  'ἀγρός': 'field, farm',
  'ἅπτω': 'touch; kindle; hold',
  'ἄρτι': 'now, just now',
  'ἐπιστρέφω': 'turn back to; turn, turn around',
  'Ἰωσήφ': 'Joseph',
  'καλῶς': 'well, beautifully',
  'καυχάομαι': 'boast, glory',
  'μαρτυρία': 'witness, testimony',
  'μάρτυς': 'witness',
  'ὀπίσω': 'behind, back',
  'ὀργή': 'anger, indignation',
  'οὖς': 'ear',
  'ὀφείλω': 'owe, ought',
  'παραγίνομαι': 'come; am present',
  'περιτομή': 'circumcision',
  'πρόβατον': 'sheep',
  'προσευχή': 'prayer',
  'Σατανᾶς': 'Satan, the Adversary',
  'Φίλιππος': 'Philip',
  'ὥσπερ': 'just as, as',
  'ἀναγινώσκω': 'read',
  'ἅπας': 'all, every',
  'ἄρα': 'then, therefore, since, so',
  'ἀρνέομαι': 'deny',
  'ἀσθενέω': 'am weak, sick',
  'βιβλίον': 'book, scroll',
  'βλασφημέω': 'blaspheme',
  'δείκνυμι': 'point out, show',
  'διαθήκη': 'covenant, will, testament',
  'διακονία': 'service',
  'δυνατός': 'powerful, able, possible',
  'ἐκπορεύομαι': 'go out',
  'μέλος': 'member, part',
  'μετανοέω': 'repent, am converted',
  'μήτε': 'nor, neither, and not',
  'ναί': 'yes, indeed',
  'οἶνος': 'wine',
  'ποῖος': 'of what kind? which? what?',
  'πτωχός': 'poor',
  'ὑποστρέφω': 'turn back, return',
  'ἀκάθαρτος': 'unclean, impure',
  'ἄνεμος': 'wind',
  'ἐλπίζω': 'hope, expect',
  'ἔξεστι': 'it is permitted, lawful, possible',
  'ἐχθρός': 'hostile; (as an noun) enemy,',
  'ἥλιος': 'sun, sunlight',
  'ἱερεύς': 'priest',
  'καθαρίζω': 'make clean; purify',
  'ὁμοίως': 'so, likewise, similarly',
  'παραγγέλλω': 'command, charge',
  'παρρησία': 'confidence, openness',
  'πλῆθος': 'multitude, crowd',
  'πλήν': 'but, except',
  'ποτέ': 'once, formerly',
  'ποτήριον': 'drinking cup, a drink',
  'συνείδησις': 'conscience',
  'ὑπομονή': 'endurance, steadfastness, patience',
  'φαίνω': 'shine, (mid.) appear, become visible',
  'φυλάσσω': 'keep, guard, observe; watch',
  'φυλή': 'tribe, race, nation',
  'ἀγοράζω': 'buy',
  'ἀρνίον': 'lamb, sheep',
  'γνῶσις': 'knowledge, wisdom',
  'διάκονος': 'waiter, servant, deacon',
  'διδαχή': 'teaching, doctrine',
  'ἐγγύς': 'near',
  'ἐλεέω': 'pity, have mercy',
  'ἐπικαλέω': 'name; (mid.) call upon',
  'ἐπιτιμάω': 'rebuke, admonish; reprove',
  'Ἠλίας': 'Elijah',
  'Καῖσαρ': 'Caesar, emperor',
  'μάχαιρα': 'sword',
  'μισθός': 'wages, reward',
  'παράκλησις': 'exhortation, entreaty',
  'παρέρχομαι': 'pass by, (pass.) pass away',
  'πάσχα': 'the feast of Passover, the Passover lamb',
  'πόθεν': 'whence',
  'προσκαλέω': 'call, invite',
  'σκότος': 'darkness',
  'συνέρχομαι': 'come with, accompany',
  'ἁγιάζω': 'make holy, sanctify',
  'ἀδικέω': 'do wrong, treat (someone) unjustly',
  'ἀληθινός': 'true, real, genuine',
  'Βαρναβᾶς': 'Barnabas',
  'βαστάζω': 'carry, carry away, bear',
  'γαμέω': 'marry',
  'ἐνδύω': 'put on, clothe',
  'ἡγέομαι': 'lead, guide; think',
  'θυγάτηρ': 'daughter',
  'θυσία': 'sacrifice, offering',
  'ἰσχυρός': 'strong, mighty, powerful',
  'ἰσχύω': 'am strong, able; am powerful',
  'νικάω': 'conquer, overcome',
  'πλούσιος': 'rich',
  'προφητεύω': 'foretell, prophesy',
  'σκανδαλίζω': 'cause to stumble',
  'τελέω': 'end, accomplish',
  'φεύγω': 'flee, escape',
  'φίλος': 'beloved, loving; (as a noun) friend',
  'χώρα': 'region, land, fields, country',
  'ἀδελφή': 'sister',
  'ἀληθής': 'unconcealed, true',
  'ἀποκαλύπτω': 'uncover, bring to light, reveal',
  'γνωρίζω': 'make known, declare, reveal',
  'δέκα': 'ten',
  'ἐκεῖθεν': 'thence, from that place, from there',
  'ἐκχέω': 'pour out, shed',
  'ἔλεος': 'pity, mercy, compassion',
  'Ἕλλην': 'Hellene, a Greek',
  'ἕνεκα': '(with gen.) because of, on account of',
  'ἐπεί': 'because, since, for',
  'Ἰακώβ': 'Jacob',
  'καταργέω': 'bring to naught, sever, abolish; make ineffective',
  'κρίμα': 'judgment, verdict, lawsuit, condemnation',
  'κώμη': 'village',
  'μυστήριον': 'anything hidden, mystery; secret rites',
  'οὔπω': 'not yet',
  'πόσος': 'how much, how great, how many?',
  'σός': 'yours, thy, thine, your',
  'σταυρός': 'cross',
  'ἀδικία': 'unrighteousness, wrongdoing',
  'Αἴγυπτος': 'Egypt',
  'ἀναβλέπω': 'look up, recover my sight; gain sight',
  'ἀσθενής': 'weak, infirm, sick, powerless',
  'δένδρον': 'tree',
  'δουλεύω': 'am a slave, am subject to, serve, obey',
  'ἑορτή': 'festival, feast',
  'ἥκω': 'have come, am present',
  'ἰάομαι': 'heal',
  'καθαρός': 'clean, pure, unstained',
  'κελεύω': 'command, order, urge',
  'λευκός': 'white, bright',
  'λυπέω': '(act.) cause someone distress, offense, pain; (pass.) am sad, grieve',
  'ὀμνύω': 'swear, take an oath',
  'ὁμολογέω': 'confess, profess, acknowledge, praise',
  'πνευματικός': 'spiritual',
  'στρατιώτης': 'soldier',
  'συνίημι': 'consider, understand; comprehend',
  'φρονέω': 'think, judge, observe',
  'χήρα': 'widow',
  'ἀκοή': 'hearing, faculty of hearing, ear, report',
  'ἀναιρέω': 'take up, abolish, murder; take away, destroy',
  'ἀσθένεια': 'want of strength, weakness, illness',
  'ἀστήρ': 'star',
  'διότι': 'on this account, because, for, therefore',
  'ἐπιστολή': 'letter, dispatch, epistle',
  'καταλείπω': 'leave behind, abandon',
  'κεῖμαι': 'lie, recline, am laid',
  'μανθάνω': 'learn, ascertain',
  'νέος': 'young, new, fresh',
  'νεφέλη': 'cloud',
  'νοῦς': 'mind, reasoning faculty, understanding',
  'οὗ': 'where, whither, when',
  'παῖς': 'boy or girl child',
  'πάρειμι': 'am present, am near',
  'παρουσία': 'presence, coming, arrival, advent',
  'πίμπλημι': 'fill, fulfill',
  'πορνεία': 'fornication, idolatry, prostitution, unchastity',
  'προσέχω': 'pay attention to, devote myself to',
  'φιλέω': 'love, like; kiss',
  'ἀμπελών': 'vineyard',
  'ἀνάγω': 'lead up, put to sea, set sail',
  'ἄπιστος': 'unbelieving, incredulous, faithless',
  'εἰκών': 'image, likeness, bust',
  'ἐλεύθερος': 'free, delivered from obligation',
  'ζῷον': 'animal, living thing',
  'θεάομαι': 'see, behold, contemplate, visit; look at',
  'θυσιαστήριον': 'altar',
  'κατηγορέω': 'accuse, charge, prosecute',
  'κοιλία': 'belly, womb, inner man',
  'κωλύω': 'prevent, hinder, forbid',
  'μιμνῄσκω': 'remember, recall',
  'πεινάω': 'am hungry, hunger, needy',
  'πέραν': 'over, beyond, across',
  'περιβάλλω': 'cast around, clothe; put on',
  'σκεῦος': 'vessel to contain liquid, utensil, jar',
  'σωτήρ': 'savior, deliverer, preserver',
  'τελειόω': 'complete, accomplish, make perfect',
  'Τιμόθεος': 'Timothy',
  'χαρίζομαι': 'show favor to, forgive, give freely',
  'ἀγνοέω': 'do not know, am ignorant of',
  'ἀντί': '(with gen.) in place of, for, instead of',
  'αὐξάνω': 'cause to increase, become greater, grow, increase',
  'γρηγορέω': 'am awake, am vigilant, watch',
  'δοκιμάζω': 'put to the test, prove, examine, approve',
  'ἐκλέγω': 'choose, select, elect',
  'ἐκλεκτός': 'chosen, elect',
  'Ἠσαΐας': 'Isaiah',
  'καθεύδω': 'sleep, am sleeping',
  'κἀκεῖνος': 'and he, she, it, and that, and that one',
  'κατεργάζομαι': 'produce, acommplish, bring about',
  'κοπιάω': 'grow weary, toil, work',
  'Μακεδονία': 'Macedonia',
  'μετάνοια': 'repentance, change of mind, conversion',
  'μηκέτι': 'no longer',
  'πληγή': 'blow, stripe, wound',
  'πλοῦτος': 'riches, wealth',
  'πωλέω': 'sell',
  'χιλιάς': 'thousand; (a group of) a thousand',
  'αἰτία': 'cause, reason',
  'ἀργύριον': 'silver, shekel, money in general',
  'βασιλεύω': 'rule, reign, reign over',
  'διδασκαλία': 'instruction, teaching',
  'ἐνεργέω': 'work, produce; accomplish',
  'εὐδοκέω': 'am resolved, well-pleased; am pleased with',
  'θερίζω': 'reap, gather; harvest',
  'καθίστημι': 'set, constitute, establish, appoint, conduct',
  'λατρεύω': 'serve, worship',
  'μνημονεύω': 'remember, mention; make mention of',
  'πειρασμός': 'trial, testing, temptation',
  'περισσός': 'abundant, greater, superfluous',
  'στρέφω': 'turn, change; am converted',
  'συνέδριον': 'council, Sanhedrin, high council',
  'τελώνης': 'collector of taxes, tax collector',
  'τεσσεράκοντα': 'forty',
  'τιμάω': 'value at a price, honor',
  'ὑπακούω': 'listen, obey',
  'χιλίαρχος': 'military tribune; leader of a thousand soldiers',
  'ὡσεί': 'as if, as it were, like, about, as',
  'ἀκροβυστία': 'foreskin; uncircumcision, the Gentiles',
  'βάπτισμα': 'rite of baptism',
  'γένος': 'offspring, family, race, kind, stock',
  'γονεύς': 'parent, parents',
  'ἑκατοντάρχης': 'centurion, captain',
  'ἐπίγνωσις': 'knowledge, discernment, recognition, understanding',
  'ἐφίστημι': 'stand by, am urgent, befall one, impend; approach, appear',
  'ἡγεμών': 'governor, procurator',
  'Ἰσαάκ': 'Isaac',
  'ἰχθύς': 'fish',
  'μαρτύριον': 'witness, evidence, testimony, proof',
  'νηστεύω': 'fast',
  'ξύλον': 'staff, cross, anything made of wood, wood, tree',
  'προάγω': 'lead forth, go before, lead forward',
  'σκηνή': 'tent, tabernacle, dwelling',
  'σοφός': 'wise',
  'τοσοῦτος': 'so great, so far, so much',
  'τρέχω': 'run, exercise myself',
  'ὑπηρέτης': 'servant, attendant, assistant',
  'ὑψόω': 'lift up, exalt',
  'ἀληθῶς': 'truly, really, certainly',
  'Ἀντιόχεια': 'Antioch',
  'ἀπέχω': 'have in full, am far, it is enough; receive, am distant, abstain',
  'γεωργός': 'worker of soil, husbandman, vine-dresser, farmer',
  'διακρίνω': 'distinguish, discern, differentiate; doubt, hesitate',
  'δῶρον': 'gift, present',
  'ἐπαίρω': 'raise, lift up, hold up',
  'ἐπάνω': 'on the top, above, superior to, over',
  'ἐπιλαμβάνομαι': 'seize, take hold of, catch',
  'ἐπουράνιος': 'heavenly, celestial',
  'κοινωνία': 'participation, communion, fellowship',
  'κριτής': 'judge',
  'κρύπτω': 'hide, conceal, lay up',
  'κτίσις': 'creation, creature, institution',
  'μεριμνάω': 'am anxious, am distracted; care for',
  'παλαιός': 'old, ancient, worn out',
  'παράπτωμα': 'falling away, sin, transgression',
  'παρατίθημι': 'set before, serve, entrust to, place besides, place around',
  'προφητεία': 'prophecy',
  'τέλειος': 'perfect, full-grown, complete',
  'ἀποκάλυψις': 'unveiling, uncovering, revealing, revelation',
  'ἀπώλεια': 'destruction, ruin, loss',
  'ἆρα': 'a particle asking a question, expecting a negative response',
  'ἀριθμός': 'number, total',
  'Ἀσία': 'roughly western third of Asia Minor, Asia',
  'βλασφημία': 'abusive language, scurrilous language, blasphemy',
  'δέησις': 'supplication, prayer, entreaty',
  'δεσμός': 'bond, chain, fetter',
  'εἰσπορεύομαι': 'journey into, go into, go in',
  'ἐλέγχω': 'rebuke, expose, convict, convince',
  'ἐμβαίνω': 'go in, embark',
  'ἐπιβάλλω': 'throw upon, lay, strike upon, put around, clothe',
  'ἐπιτρέπω': 'allow, permit',
  'θυμός': 'outburst of passion, wrath, anger',
  'καταγγέλλω': 'declare openly, preach, proclaim',
  'κατακρίνω': 'condemn',
  'κατέχω': 'hold back, hold fast, bind, restrain',
  'κενός': 'empty, vain, hollow',
  'κληρονομέω': 'inherit, acquire, obtain',
  'κοιμάομαι': 'fall asleep, am asleep, sleep, die',
  'ἀνάγκη': 'necessity, constraint, compulsion, distress',
  'ἀρέσκω': 'please, serve',
  'ἄφεσις': 'deliverance, pardon, forgiveness',
  'βρῶμα': 'food of any kind',
  'κόπος': 'trouble, toil, labor, work',
  'μέχρι': 'as far as, until',
  'μήν': 'month',
  'νυνί': 'now, already, at present',
  'οἰκοδομή': 'act of building, building, edification',
  'παραχρῆμα': 'instantly, immediately',
  'ποιμήν': 'shepherd',
  'πόλεμος': 'war, battle, strife',
  'πολλάκις': 'many times, often',
  'προστίθημι': 'put to, add, do again',
  'πυλών': 'large gate, gateway, porch',
  'στέφανος': 'crown, garland',
  'ταράσσω': 'agitate, stir up, trouble',
  'τίκτω': 'bear, bring forth, produce, give birth to',
  'φανερός': 'apparent, clear, visible, manifest',
  'χρυσοῦς': 'golden',
  'ἑκατόν': 'one hundred',
  'ἐξίστημι': 'am amazed, am astonished, astonish',
  'ἐπαύριον': 'tomorrow',
  'ἕτοιμος': 'ready, prepared',
  'θησαυρός': 'treasure, store',
  'ἵππος': 'horse',
  'καθάπερ': 'even as, as, just as',
  'Καισάρεια': 'Caesarea',
  'καταλύω': 'destroy, abolish, break up, overthrow, unharness, find a lodging',
  'κερδαίνω': 'gain, win, avoid loss',
  'κρυπτός': 'hidden, secret',
  'μήτι': 'if not, unless, (a usually untranslated particle in questions that expect a negative answer)',
  'νίπτω': 'wash',
  'περιτέμνω': 'circumcise',
  'πλήρωμα': 'fullness, fulfillment, completion',
  'πλησίον': 'near, nearby, a neighbor',
  'ποταμός': 'river, torrent, stream',
  'ῥίζα': 'root, that which comes from root',
  'ῥύομαι': 'save, rescue',
  'σκοτία': 'darkness',
  'ἀθετέω': 'reject, annul',
  'ἀνακρίνω': 'question, examine, inquire into',
  'δεῖπνον': 'dinner, afternoon or evening meal, supper',
  'δέσμιος': 'prisoner',
  'δηνάριον': 'denarius',
  'διαλογίζομαι': 'reason, debate, consider',
  'διατάσσω': 'give orders to, prescribe, order, direct',
  'διψάω': 'thirst for, desire earnestly, thirst',
  'ἐκτείνω': 'stretch out, cast forth, extend',
  'ἔπειτα': 'then, thereafter, afterwards',
  'ἐπιθυμέω': 'desire, long for, covet, lust after',
  'ἐπιμένω': 'remain, stay, tarry, persist in',
  'ἐργάτης': 'field-laborer, workman, doer',
  'εὐλογία': 'adulation, praise, blessing',
  'Ἔφεσος': 'Ephesus',
  'ὑποκριτής': 'hypocrite, dissembler',
  'ὑπομένω': 'remain behind, remain, endure',
  'χάρισμα': 'undeserved favor, a gift',
  'ὦ': 'O, an exclamation, O!, Oh!',
  'ὡσαύτως': 'likewise',
  'ζῆλος': 'eagerness, zeal, rivalry, jealousy',
  'θεμέλιος': 'belonging to foundation',
  'κακῶς': 'badly, wickedly',
  'κἄν': 'and if, even if, if only',
  'Καφαρναούμ': 'Capernaum',
  'κλείω': 'shut, shut up, lock',
  'κλέπτης': 'thief',
  'λύπη': 'pain, grief, sorrow',
  'νυμφίος': 'bridegroom',
  'οὐδέποτε': 'never',
  'πάθημα': 'suffering, passion',
  'παρέχω': 'offer, provide, give, cause',
  'περισσῶς': 'greatly, exceedingly',
  'πλήρης': 'full, complete',
  'προσδοκάω': 'expect, await, wait for',
  'συκῆ': 'fig tree',
  'συλλαμβάνω': 'seize, conceive, apprehend, become pregnant',
  'συνίστημι': 'commend, prove, am composed of, cohere, present, introduce',
  'σφραγίς': 'signet-ring, impression of seal, proof',
  'τέρας': 'wonder, portent',
  'ἀνέχομαι': 'endure, bear with',
  'ἀνομία': 'lawlessness, iniquity',
  'γάμος': 'marriage, wedding, wedding-feast',
  'γέ': 'at least, indeed, really; (usually untranslatable particle, emphasizing the word it follows)',
  'γεύομαι': 'taste, experience, come to know',
  'γνωστός': 'known, an acquaintance',
  'γυμνός': 'wearing only the under-garment, bare, naked',
  'Δαμασκός': 'Damascus',
  'δέρω': 'flay, flog, scourge, beat',
  'διαμαρτύρομαι': 'give solemn evidence, testify solemnly, solemnly declare',
  'εἶτα': 'then, thereafter, next',
  'ἐλαία': 'olive tree',
  'ἐντέλλομαι': 'give orders, command, order',
  'ἐπαγγέλλομαι': 'promise, profess',
  'ἐπίσταμαι': 'know, understand',
  'εὐσέβεια': 'piety, godliness',
  'εὐχαριστία': 'thankfulness, gratitude, thanksgiving',
  'τολμάω': 'dare, endure, am bold',
  'τροφή': 'food, nourishment',
  'ὑστερέω': 'am lacking, fall short, suffer need; (pass.) lack',
  'θρίξ': 'hair',
  'Ἰορδάνης': 'Jordan',
  'καταλαμβάνω': 'seize tight hold of, overtake, comprehend, seize, win',
  'κατέρχομαι': 'come down',
  'κληρονόμος': 'heir, inheritor',
  'κτίζω': 'create, form, shape, make',
  'Λάζαρος': 'Lazarus, Eliezer',
  'λῃστής': 'robber, brigand, bandit',
  'μοιχεύω': 'commit adultery',
  'νομίζω': 'think, believe, suppose',
  'ξηραίνω': 'dry, dry up, parch, ripen',
  'ὅθεν': 'whence, wherefore, from where',
  'οἰκουμένη': 'inhabited (Roman) world',
  'ὁμοιόω': 'make like, liken, compare',
  'παρθένος': 'virgin',
  'παύομαι': 'cease, cause to cease',
  'πέτρα': 'rock, stone',
  'ποτίζω': 'cause to drink, give to drink',
  'προλέγω': 'forewarn, tell beforehand',
  'ῥαββί': 'Rabbi, my master, teacher',
  'ἄκανθα': 'thorn-bush, thorn-plant',
  'ἀλλότριος': 'belonging to another person, foreign, belonging to another, strange',
  'ἀμφότεροι': 'both of two, both, all',
  'ἀνάκειμαι': 'recline, especially at a dinner-table, lie',
  'ἀναχωρέω': 'return, retire, depart, withdraw, go away, take refuge',
  'ἀνθίστημι': 'take a stand against, oppose, resist',
  'ἀπάγω': 'lead, carry, take away, lead away',
  'ἅπαξ': 'once, once for all',
  'ἀπειθέω': 'disobey, rebel, am disloyal, am disobedient',
  'ἁρπάζω': 'seize, snatch, obtain by robbery, steal',
  'σαλεύω': 'shake, excite',
  'Σαῦλος': 'Saul',
  'σκάνδαλον': 'snare, stumbling-block, that which gives offense, temptation to sin',
  'συμφέρω': 'collect, am profitable to, help',
  'σφραγίζω': 'set a seal upon, seal',
  'τράπεζα': 'table for food or business, table',
  'ὑπακοή': 'obedience',
  'χορτάζω': 'feed, satisfy, fill; (pass.) eat my fill',
  'χόρτος': 'grass, hay',
  'ὠφελέω': 'help, benefit, do good',
  'ἀτενίζω': 'direct my gaze, look steadily, look intently',
  'αὔριον': 'tomorrow',
  'ἀφίστημι': 'lead away, seduce, depart, abstain from, go away',
  'γράμμα': 'letter (of the alphabet), writings, learning',
  'διαλογισμός': 'calculation, reasoning, thought, plotting, doubt, dispute',
  'ἕκτος': 'sixth',
  'ἐνιαυτός': 'year',
  'ἐξαποστέλλω': 'send forth',
  'εὐφραίνω': 'gladden, cheer, make merry; (pass.) am glad',
  'θύω': 'sacrifice, kill',
  'κατανοέω': 'understand, perceive, consider',
  'κατεσθίω': 'eat till it is finished, eat up, devour',
  'κλάω': 'break',
  'κληρονομία': 'inheritance, possession',
  'κοινός': 'common, shared, unclean, communal',
  'κοινόω': 'make unclean, regard as unclean, make common, defile',
  'κρείττων': 'stronger, more excellent, better',
  'κωφός': 'dumb, deaf, mute',
  'λύχνος': 'lamp',
  'μακρόθεν': 'from a distance, from far away',
  'μακροθυμία': 'patience, forbearance, steadfastness',
  'μερίζω': 'divide, part, share, separate',
  'μέτρον': 'measure, measuring rod',
  'μύρον': 'anointing-oil, ointment, perfume',
  'νήπιος': 'an infant, child, unlearned, a minor',
  'νοέω': 'understand, consider, perceive',
  'ξένος': 'new, novel, a foreigner, strange, foreign',
  'οἷος': 'of what kind, such as, of what sort',
  'ὄφις': 'serpent, snake',
  'ὄψιος': 'late, evening',
  'πετεινόν': 'bird',
  'προσδέχομαι': 'welcome, accept, receive; expect, wait for',
  'Σαδδουκαῖος': 'Sadducee',
  'σεισμός': 'earthquake, storm, shaking',
  'σῖτος': 'wheat, grain',
  'στηρίζω': 'fix firmly, strengthen, establish',
  'τάλαντον': 'talent of silver or gold',
  'ταπεινόω': 'humble, humiliate, make low',
  'τύπος': 'figure, model, type, image, copy',
  'φρόνιμος': 'intelligent, prudent, sensible, thoughtful',
  'ἀνά': 'by, each, every, in, through, (with acc.) up; (with numbers) each',
  'ἀναγγέλλω': 'announce, make known, report, proclaim',
  'ἀναλαμβάνω': 'take up, raise',
  'ἀναστροφή': 'behavior, manner of life, way of life, conduct',
  'Ἀνδρέας': 'Andrew',
  'ἄνωθεν': 'from above, from the beginning, again',
  'δαιμονίζομαι': 'am demon-possessed',
  'διαλέγομαι': 'converse, address, preach, lecture, discuss',
  'διαφέρω': 'carry through, differ, surpass, excel, am superior',
  'δράκων': 'dragon or huge serpent',
  'ἐκπλήσσομαι': 'astounded, am amazed, overwhelmed',
  'ἐλάχιστος': 'least, smallest, very little',
  'ἐλεημοσύνη': 'alms-giving, charity, alms',
  'ἐμπαίζω': 'mock, ridicule',
  'ἕξ': 'six',
  'ἔξωθεν': 'from without, outside, from the outside',
  'ἐπιζητέω': 'seek after, desire, search for, strive for',
  'ζύμη': 'leaven, ferment, yeast',
  'φύσις': 'nature, inherent nature',
  'χωλός': 'lame, deprived of a foot',
  'θερισμός': 'reaping, harvest',
  'καπνός': 'smoke',
  'καταισχύνω': 'shame, disgrace, put to utter confusion, put to shame, dishonor',
  'καταντάω': 'come down, arrive at, reach, come to, approach',
  'καταρτίζω': 'fit together, prepare, mend, perfect',
  'κλέπτω': 'steal',
  'Μάρθα': 'Martha',
  'Ναζωραῖος': 'Nazarene, Nazorean',
  'παιδεύω': 'discipline, educate, train, chastise, bring up',
  'παιδίσκη': 'female slave, maidservant, maid.',
  'παράδοσις': 'instruction, tradition, handing over',
  'πρίν': 'formerly, before',
  'τίμιος': 'of great price, precious, honored, valuable',
  'Τίτος': 'Titus',
  'τρόπος': 'way, manner, character, kind',
  'τύπτω': 'beat, strike, wound, inflict punishment',
  'ὕψιστος': 'highest, most high, the heights, most exalted',
  'Φῆστος': 'Festus',
  'χρυσίον': 'golden ornament, gold',
  'ἄδικος': 'unjust, unrighteous',
  'ἀναπαύω': 'make to rest, give rest to, rest, refresh',
  'ἀναπίπτω': 'lie down, recline, fall back upon',
  'ἀσκός': 'wine-skin',
  'αὐλή': 'court-yard, fore-court, palace, house, court',
  'Βαβυλών': 'Babylon',
  'βαπτιστής': 'baptizer, Baptist',
  'βασανίζω': 'torment, torture, buffet',
  'Βηθανία': 'Bethany',
  'βῆμα': 'space covered by step of foot, tribunal, step, judge’s bench, platform',
  'βοάω': 'shout, call aloud, call',
  'βουλή': 'counsel, wisdom, purpose',
  'βροντή': 'thunder',
  'γέεννα': 'Gehenna, hell',
  'γόνυ': 'knee',
  'δεῦτε': 'come hither!, come!, come (on)!',
  'διάνοια': 'understanding, intellect, mind',
  'δίκτυον': 'fishing-net, net',
  'ἔθος': 'custom, law',
  'χωρίζω': 'divide, separate, depart',
  'ἐξάγω': 'lead out',
  'ἔσωθεν': 'inside, within; from within',
  'Ζεβεδαῖος': 'Zebedee, Zebedec',
  'καίω': 'ignite, light, burn',
  'κάλαμος': 'reed, reed-pen',
  'κατακαίω': 'burn up, consume entirely, burn down',
  'κατάκειμαι': 'recline, am lying ill, lie down',
  'κολλάομαι': 'glue, cleave, keep company with, cling to, join',
  'κράτος': 'dominion, strength, power, rule',
  'λίαν': 'very, very much, exceedingly',
  'λιμός': 'famine, hunger',
  'λυχνία': 'lamp-stand, lampstand',
  'Μαγδαληνή': 'Magdalene, woman from Magdala',
  'μάλιστα': 'most of all, especially',
  'μεταβαίνω': 'leave, depart, remove, pass over, go over, move',
  'μωρός': 'stupid, foolish',
  'Ναζαρά': 'Nazareth',
  'ὀδούς': 'tooth',
  'οἰκοδεσπότης': 'head of household, the master of the house',
  'ὅριον': 'districts, territory, region',
  'παραιτέομαι': 'make excuse, refuse, reject, ask for',
  'πιάζω': 'lay hold of, seize, catch',
  'πληθύνω': 'increase, multiply',
  'πλουτέω': 'become rich, am rich',
  'πόρνη': 'prostitute',
  'πρόθεσις': 'show-bread, predetermination, presentation; plan',
  'προσλαμβάνομαι': 'take to myself, welcome, receive, accept',
  'πρωΐ': 'early (in the morning), at dawn',
  'πῶλος': 'colt, young ass, ass’s foal, young donkey',
  'ῥάβδος': 'rod, staff',
  'Ῥωμαῖος': 'Roman, a Roman citizen',
  'σαλπίζω': 'sound a trumpet, trumpet',
  'Σιλᾶς': 'Silas',
  'Σολομών': 'Solomon',
  'σπλαγχνίζομαι': 'have pity on, feel sympathy for',
  'σπουδή': 'haste; diligence, eagerness',
  'συνεργός': 'a fellow worker, helper',
  'συνέχω': 'press together, confine, compel, oppress, attack',
  'ταχύς': 'quickly, speedily, quick',
  'τρίς': 'three times',
  'ἀγαλλιάω': 'exult, am full of joy, am glad',
  'ἀγορά': 'market-place',
  'Ἀγρίππας': 'Agrippa',
  'ἀλέκτωρ': 'cock, rooster',
  'ἅλυσις': 'light chain, chain',
  'Ἁνανίας': 'Ananias',
  'ἀνατολή': 'rising of sun, East, rising',
  'ἀντιλέγω': 'speak or say in opposition, contradict, object to, oppose',
  'ἀπαρνέομαι': 'deny, disown, disregard',
  'ἀπιστία': 'unbelief, unfaithfulness, distrust',
  'ἀρχαῖος': 'original, primitive, ancient, old',
  'ἄφρων': 'senseless, foolish, inconsiderate, ignorant',
  'Βαραββᾶς': 'Barabbas',
  'τυγχάνω': 'obtain, happen, perhaps, meet',
  'ὑγιαίνω': 'am well, am healthy, sound',
  'ὑγιής': 'sound, whole, wholesome, healthy',
  'φιάλη': 'shallow and flat bowl, bowl',
  'φονεύω': 'murder, kill',
  'χοῖρος': 'swine',
  'ψεύδομαι': 'lie',
  'βρῶσις': 'eating, food, meal, rust',
  'Γαλιλαῖος': 'Galilean',
  'γέμω': 'am full of, am full',
  'διαμερίζω': 'divide up into parts, break up, distribute',
  'δόλος': 'deceit, guile, treachery',
  'δωρεά': 'free gift, gift, bounty',
  'ἐάω': 'allow, permit, leave, let go, leave alone',
  'εἴδωλον': 'idol, false god, image',
  'εἰσάγω': 'lead in, bring in, lead into',
  'ἔλαιον': 'olive oil, oil',
  'ἐλευθερία': 'freedom, liberty',
  'ἐμβλέπω': 'look into, look upon, look at',
  'ἐνδείκνυμι': 'show forth, show, demonstrate',
  'ἐξουθενέω': 'ignore, despise, reject',
  'ἔπαινος': 'commendation, praise',
  'ἐπαισχύνομαι': 'am ashamed',
  'ἐπιπίπτω': 'fall upon, press upon',
  'ἐπισκέπτομαι': 'look upon, visit, look out, select, oversee, care for',
  'Ζαχαρίας': 'Zechariah',
  'ζηλόω': 'am jealous, am zealous, eager for',
  'ζῳοποιέω': 'make to live, make alive',
  'θανατόω': 'put to death, subdue, kill',
  'θάπτω': 'bury',
  'Θωμᾶς': 'Thomas',
  'Ἰσκαριώθ': 'Iscariot, man of Kerioth',
  'κακία': 'evil, wickedness, malice',
  'καταβολή': 'foundation, depositing, sowing',
  'κατασκευάζω': 'build, prepare, make, furnish',
  'κάτω': 'down, below, lower, under, less, downward',
  'καύχημα': 'boasting, object of boasting',
  'καύχησις': 'act of boasting, exultation, boasting',
  'κέρας': 'horn',
  'κλάδος': 'branch',
  'κλῆρος': 'lot, portion, share',
  'κλῆσις': 'calling, summons',
  'κομίζω': 'bring, receive, recover',
  'κράβαττος': 'bed, mattress, mat',
  'λίμνη': 'lake',
  'μετρέω': 'measure, estimate',
  'νεανίσκος': 'young man, youth',
  'νόσος': 'disease, malady, illness',
  'ὁμοθυμαδόν': 'with one mind, unanimously',
  'ὅραμα': 'spectacle, (supernatural) vision',
  'πηγή': 'fountain, spring, well',
  'ποιμαίνω': 'shepherd, tend, pasture',
  'πρᾶγμα': 'thing done, matter, deed, thing',
  'πραΰτης': 'mildness, gentleness, meekness, humility',
  'πρότερος': 'formerly, before, earlier',
  'πυνθάνομαι': 'ask, inquire',
  'σάλπιγξ': 'trumpet',
  'Σαμάρεια': 'Samaria',
  'σπλάγχνον': 'bowels, compassion, pity, heart, love, sympathy',
  'σπουδάζω': 'hasten; am eager',
  'στήκω': 'stand fast, persevere, stand, stand firm',
  'συγγενής': 'akin, akin to, a relative, related',
  'σφόδρα': 'exceedingly, greatly, very (much)',
  'σχίζω': 'rend, divide asunder, split',
  'τελευτάω': 'end, finish, die',
  'τριάκοντα': 'thirty',
  'ἁγιασμός': 'sanctification, holiness',
  'ᾅδης': 'Hades',
  'ἀδύνατος': 'incapable, impossible, powerless',
  'ἀκαθαρσία': 'uncleanness, impurity, immorality',
  'ἅμα': 'at the same time, along with, together',
  'ἀναφέρω': 'carry up, lead up, offer up, bring up, take up',
  'Ἀπολλῶς': 'Apollos',
  'ἀπολογέομαι': 'give a defense, defend myself',
  'ἀπολύτρωσις': 'redemption, deliverance, release',
  'Τύρος': 'Tyre',
  'ὑποκάτω': 'underneath, under',
  'ὕστερος': 'lastly, afterward, later, finally',
  'ὑψηλός': 'high, lofty',
  'φυτεύω': 'plant',
  'φωτίζω': 'illuminate, bring to light',
  'χείρων': 'worse',
  'χίλιοι': 'a thousand, thousands',
  'χιτών': 'tunic, garment, undergarment',
  'χράομαι': 'use, make use of, deal with',
  'ψευδοπροφήτης': 'false prophet',
  'ἀσέλγεια': 'wantonness, lewdness, licentiousness, sensuality',
  'ἀσπασμός': 'greeting, salutation',
  'ἀφαιρέω': 'take away, smite off',
  'ἀφορίζω': 'separate, place apart',
  'Ἀχαΐα': 'Achaia',
  'βίβλος': 'written book, roll, volume, book',
  'δάκρυον': 'tear',
  'δεσπότης': 'lord, master, prince',
  'δικαίωμα': 'thing pronounced to be just; righteous deed',
  'διωγμός': 'persecution',
  'ἐγκαταλείπω': 'abandon, desert, leave behind',
  'εἴκοσι': 'twenty',
  'ἐκκόπτω': 'cut out, cut off, cut down',
  'ἐκπίπτω': 'fall out, fall off, fall away, fall from',
  'ἐμφανίζω': 'make visible, report against, appear before, reveal',
  'ἔνατος': 'ninth',
  'ἔνοχος': 'involved in, liable, guilty',
  'ἐντεῦθεν': 'hence, from this place, from here',
  'ἐξομολογέω': 'consent fully, confess',
  'ἐπειδή': 'when, since, because',
  'ἐπιτάσσω': 'give order, command, order',
  'ἐπιτελέω': 'complete, accomplish, perfect',
  'θλίβω': 'afflict, oppress, persecute',
  'Ἰόππη': 'Joppa',
  'ἰσχύς': 'strength, power',
  'κἀκεῖ': 'and there, and yonder',
  'κἀκεῖθεν': 'and thence, and from there',
  'κλητός': 'called, summoned, invited',
  'κοινωνός': 'partner, companion',
  'κοσμέω': 'put into order, adorn, beautify',
  'μακροθυμέω': 'suffer long, have patience',
  'μέλει': 'it is a care, it concerns',
  'μνῆμα': 'tomb, monument, grave',
  'ξενίζω': 'entertain, entertain a stranger',
  'ὅδε': 'this here, this',
  'οἰκονόμος': 'steward, house steward',
  'ὀκτώ': 'eight',
  'ὄντως': 'really, truly',
  'ὅρκος': 'oath',
  'παντοκράτωρ': 'ruler of universe, the Almighty',
  'παράγω': 'pass by, depart, pass away,',
  'παραλυτικός': 'afflicted with paralysis, lame; (as a noun) a paralytic',
  'παρεμβολή': 'camp, barracks',
  'πατάσσω': 'strike',
  'πενθέω': 'mourn, lament, grieve',
  'περιστερά': 'dove, pigeon',
  'πλάνη': 'wandering, error, deceit',
  'πλεονεξία': 'covetousness, greediness',
  'ποικίλος': 'various, of different colors, manifold',
  'πόρνος': 'fornicator, a sexually immoral person',
  'προσκαρτερέω': 'persist, hold fast',
  'πύλη': 'door, gate',
  'σέβω': 'reverence, worship',
  'σιγάω': 'keep silent, am silent, still',
  'σιωπάω': 'keep silence, am silent',
  'στρατηγός': 'general, magistrate, captain of temple',
  'συζητέω': 'seek together, discuss',
  'σύνδουλος': 'fellow servant, colleague',
  'σφάζω': 'slay, slaughter',
  'ταχέως': 'soon, quickly, hastily',
  'τέταρτος': 'fourth',
  'ὑμέτερος': 'your',
  'ὑπαντάω': 'meet, fight, oppose',
  'ὑπόδημα': 'sandal',
  'φείδομαι': 'spare, abstain',
  'χρηστότης': 'goodness, kindness',
  'χωρέω': 'make room, receive',
  'χωρίον': 'field, land',
  'ψεῦδος': 'lie',
  'ψεύστης': 'liar, deceiver',
}
